// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ToolId        string                 `protobuf:"bytes,2,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Cost          int32                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CheckRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *CheckRequest) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_proto_policy_v1_policy_proto protoreflect.FileDescriptor

const file_proto_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/policy/v1/policy.proto\x12\x12sentinel.policy.v1\"V\n" +
	"\fCheckRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atool_id\x18\x02 \x01(\tR\x06toolId\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\"m\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs2]\n" +
	"\rPolicyService\x12L\n" +
	"\x05Check\x12 .sentinel.policy.v1.CheckRequest\x1a!.sentinel.policy.v1.CheckResponseBAZ?github.com/thisaruRasanjana/Sentinel/policy-engine/pkg/policyv1b\x06proto3"

var (
	file_proto_policy_v1_policy_proto_rawDescOnce sync.Once
	file_proto_policy_v1_policy_proto_rawDescData []byte
)

func file_proto_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_proto_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_proto_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_policy_v1_policy_proto_rawDesc), len(file_proto_policy_v1_policy_proto_rawDesc)))
	})
	return file_proto_policy_v1_policy_proto_rawDescData
}

var file_proto_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_policy_v1_policy_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: sentinel.policy.v1.CheckRequest
	(*CheckResponse)(nil), // 1: sentinel.policy.v1.CheckResponse
}
var file_proto_policy_v1_policy_proto_depIdxs = []int32{
	0, // 0: sentinel.policy.v1.PolicyService.Check:input_type -> sentinel.policy.v1.CheckRequest
	1, // 1: sentinel.policy.v1.PolicyService.Check:output_type -> sentinel.policy.v1.CheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_policy_v1_policy_proto_init() }
func file_proto_policy_v1_policy_proto_init() {
	if File_proto_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_policy_v1_policy_proto_rawDesc), len(file_proto_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_proto_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_proto_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_proto_policy_v1_policy_proto = out.File
	file_proto_policy_v1_policy_proto_goTypes = nil
	file_proto_policy_v1_policy_proto_depIdxs = nil
}
