services:
  gateway:
    build:
      context: ../../gateway
    ports:
      - "8080:8080"
    environment:
      BAL_CONFIG_DATA: |
        policyUrl="http://policy-engine:9001"
        registryUrl="http://registry:9002"
        certFile="./token-issuer/resources/public.crt"
    depends_on:
      - tool-billing
      - tool-inventory
      - policy-engine
      - registry
    volumes:
      - ../../token-issuer/resources:/home/ballerina/token-issuer/resources

  tool-billing:
    build:
      context: ../../tools/tool-billing
    ports:
      - "7001:7001"

  tool-inventory:
    build:
      context: ../../tools/tool-inventory
    ports:
      - "7002:7002"

  token-issuer:
    build:
      context: ../../token-issuer
    ports:
      - "9000:9000"
    volumes:
      - ../../token-issuer/resources:/home/ballerina/resources

  policy-engine:
    build:
      context: ../../policy-engine
    ports:
      - "9001:9001"
      - "9010:9010"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  registry:
    build:
      context: ../../registry
    ports:
      - "9002:9002"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
