// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: registry.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolRequest) Reset() {
	*x = GetToolRequest{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolRequest) ProtoMessage() {}

func (x *GetToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolRequest.ProtoReflect.Descriptor instead.
func (*GetToolRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *GetToolRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type GetToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      *ToolMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolResponse) Reset() {
	*x = GetToolResponse{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolResponse) ProtoMessage() {}

func (x *GetToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolResponse.ProtoReflect.Descriptor instead.
func (*GetToolResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *GetToolResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetToolResponse) GetMetadata() *ToolMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ToolMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpstreamUrl   string                 `protobuf:"bytes,1,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`
	HttpMethod    string                 `protobuf:"bytes,2,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	RequiredScope string                 `protobuf:"bytes,3,opt,name=required_scope,json=requiredScope,proto3" json:"required_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolMetadata) Reset() {
	*x = ToolMetadata{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolMetadata) ProtoMessage() {}

func (x *ToolMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolMetadata.ProtoReflect.Descriptor instead.
func (*ToolMetadata) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ToolMetadata) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *ToolMetadata) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *ToolMetadata) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\x14sentinel.registry.v1\")\n" +
	"\x0eGetToolRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\"g\n" +
	"\x0fGetToolResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\".sentinel.registry.v1.ToolMetadataR\bmetadata\"y\n" +
	"\fToolMetadata\x12!\n" +
	"\fupstream_url\x18\x01 \x01(\tR\vupstreamUrl\x12\x1f\n" +
	"\vhttp_method\x18\x02 \x01(\tR\n" +
	"httpMethod\x12%\n" +
	"\x0erequired_scope\x18\x03 \x01(\tR\rrequiredScope2i\n" +
	"\x0fRegistryService\x12V\n" +
	"\aGetTool\x12$.sentinel.registry.v1.GetToolRequest\x1a%.sentinel.registry.v1.GetToolResponseB>Z<github.com/thisaruRasanjana/Sentinel/registry/pkg/registryv1b\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_registry_proto_goTypes = []any{
	(*GetToolRequest)(nil),  // 0: sentinel.registry.v1.GetToolRequest
	(*GetToolResponse)(nil), // 1: sentinel.registry.v1.GetToolResponse
	(*ToolMetadata)(nil),    // 2: sentinel.registry.v1.ToolMetadata
}
var file_registry_proto_depIdxs = []int32{
	2, // 0: sentinel.registry.v1.GetToolResponse.metadata:type_name -> sentinel.registry.v1.ToolMetadata
	0, // 1: sentinel.registry.v1.RegistryService.GetTool:input_type -> sentinel.registry.v1.GetToolRequest
	1, // 2: sentinel.registry.v1.RegistryService.GetTool:output_type -> sentinel.registry.v1.GetToolResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
